# Generated by Django 5.2 on 2026-03-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Byujeteriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='Suwretleri/')),
            ],
        ),
    ]
